version: '3'

services:
  db:
    container_name: mysql
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bike
      MYSQL_USER: bike_user
      MYSQL_PASSWORD: bike_password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    expose:
      - '3306'
    volumes:
      - './db/data:/var/lib/mysql'
      - './db/conf.d:/etc/mysql/conf.d'
      - './db/sql:/dokcer-entrypoint-initdb.d'
    networks:
      learnTech:

networks:
  learnTech:
